### ISSUE TITLE
variables and code must be at the same file

### ISSUE THREAD

**Issue by AMKamel** [toowoxx/terraform-provider-packer#1]
Hello there, 

Thanks a lot for starting to work on this provider.

Currently there must be one file only containing all packer code, right?

if so, is there an intention to support reading `.hcl` files inside working directory as it's with `packer build .` command?

**Comment by simaotwx** [comment]
Hi @AMKamel 

The provider is at an early stage of development. Currently you need to have only one file, correct.

I do have the intention to extend the provider to support `packer build .` as that is a common use case.

Thank you for your feedback.

**Comment by simaotwx** [comment]
Implemented in v0.7.1
