### ISSUE TITLE
Add examples/documentation for additional_params

### ISSUE THREAD

**Issue by bubthegreat** [toowoxx/terraform-provider-packer#14]
**Is your feature request related to a problem? Please describe.**
While troubleshooting builds it would be great if we can pass in additional params for the build, like the `-on-error=ask` flag or to leave the problematic images in place.

**Describe the solution you'd like**
Have documentation on the additional_params and which ones would be supported for the flags that can be used with packer build

**Describe alternatives you've considered**
Manually running the equivalent packer build command - this is fine, in the end, but it means I have to manually pull all of my context out of my command and put it in the command line, including passwords

**Additional context**
This came up as I was troubleshooting an apt update that was failing because of a package lock while cloud-init finished installing things.

**Comment by simaotwx** [comment]
`additional_params` can be used to pass any parameter that packer itself supports.
While I agree it makes sense to show some examples, it really is up to the user to look up what parameters Packer can take and pass them accordingly. There's nothing special about it, the parameters are just passed as-is to Packer.

**Comment by simaotwx** [comment]
Example added in 0.15.1
