### ISSUE TITLE
Could not load plugin

### ISSUE THREAD

**Issue by tyki6** [toowoxx/terraform-provider-packer#3]
hi,
I wanted to use your provider but i got problem during initialization.
Regards, 
# Error Message
```
Releasing state lock. This may take a few moments...

Error: Could not load plugin


Plugin reinitialization required. Please run "terraform init".

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints, run "terraform providers".

Failed to instantiate provider "registry.terraform.io/toowoxx/packer" to
obtain schema: Incompatible API version with plugin. Plugin version: 6, Client
versions: [5]
```

# I tried
- `terraform init`
- `rm -rf .terraform && terraform init` 
- `terraform init -upgrade`

# Information
terraform version: 
```
Terraform v0.14.8
+ provider registry.terraform.io/toowoxx/packer v0.8.1
```

`main.tf`:
```
terraform {
  required_providers {
    packer = {
      source = "toowoxx/packer"
      version = "0.8.1"
    }
  }
}

provider "packer" {
  # Configuration options
}
```

**Comment by simaotwx** [comment]
Hi,
thanks for submitting an issue. Could you share your OS and environment information, i.e. where you're running Terraform (Local, Terraform Cloud, CI/CD) and the OS (Windows, Linux (distro), macOS)?

**Comment by simaotwx** [comment]
I just checked your information again and noticed that you're running Terraform v0.14.8 which is not supported.
This provider should be used with a newer version such as Terraform v1.0.11
Could you try running provider version v0.8.0 or v0.7.1 and see if it helps?

Related: https://github.com/hashicorp/terraform-plugin-framework/issues/158

**Comment by simaotwx** [comment]
@mBouamama Is your issue solved? Please let me know if upgrading your Terraform version or trying a different provider version helps.

**Comment by tyki6** [comment]
Hi, 
Sorry i miss to inform you.Upgrade Terraform version to latest or use previous version of provider solved the issue.Thx mates.
Regards,
