### ISSUE TITLE
Possibly wrong use of resourceState.Directory

### ISSUE THREAD

**Issue by UncleSamSwiss** [toowoxx/terraform-provider-packer#4]
In the following lines `dir` seems not to be used (sorry, I'm not a go expert):
https://github.com/toowoxx/terraform-provider-packer/blob/9c1d43938fdeb3dfc04c1999d80a8fe355f19ed8/provider/data_source_files.go#L26-L34

I believe the two calls should be:
```diff
- filepath.Glob(resourceState.Directory.Value + ...
+ filepath.Glob(dir + ...
```

**Comment by simaotwx** [comment]
Thank you! It looks like you're correct. I'll fix this in a future version.
