### ISSUE TITLE
Recursively hash files in directory for `packer_files` data source

### ISSUE THREAD

**Issue by karelorigin** [toowoxx/terraform-provider-packer#6]
```terraform
data "packer_files" "foo" {
  directory = "${path.module}/image"
  file      = "${path.module}/image/foo.pkr.hcl"
  file_dependencies = [
    "${path.module}/foo",
  ]
}
```

Is kind of the boilerplate for a simple image with one file dependency, but I have many files in subdirectories that require an image rebuild. Any chance that we can get an option for hashing directories (recursively)?

**Comment by simaotwx** [comment]
You can do this using the Terraform built-in function [`fileset`](https://www.terraform.io/language/functions/fileset):

```
data "packer_files" "vm_image_files" {
  file              = "image.pkr.hcl"
  file_dependencies = fileset(".", "assets/**")
}
```

Note that the file denoted by `file` is already taken into account so you don't need to reference that one in `file_dependencies` (although, you can).

Let me know if this solves your use case.

**Comment by karelorigin** [comment]
Actually, yes, I think that might solve it. Thank you! :D

**Comment by simaotwx** [comment]
You're welcome! :)
